### ISSUE TITLE
在新版 mcdr 下报错

### ISSUE THREAD

**Issue by shenjackyuanjie** [TISUnion/LocationMarker#9]
```
Traceback (most recent call last):
  File "D:\APPS\CPython\Python38\lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 600, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "D:\APPS\CPython\Python38\lib\site-packages\mcdreforged\plugin\plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
  File "D:\SERVERS\DEMO\plugins\LocationMarker-v1.3.1\location_marker\entry.py", line 237, in on_load
    then(Literal('tp').QuotableText('name').runs(lambda src, ctx: tp_to(src, ctx))))
AttributeError: 'Literal' object has no attribute 'QuotableText'
```
```
!!MCDR status
[MCDR] [23:43:54] [TaskExecutor/INFO]: MCDReforged 版本: 2.12.3
[MCDR] [23:43:54] [TaskExecutor/INFO]: MCDR 状态: 运行中
[MCDR] [23:43:54] [TaskExecutor/INFO]: 服务端状态: 运行中
[MCDR] [23:43:54] [TaskExecutor/INFO]: 服务端已启动: True
[MCDR] [23:43:54] [TaskExecutor/INFO]: 将于服务端关闭后退出: True
[MCDR] [23:43:54] [TaskExecutor/INFO]: rcon: 离线
[MCDR] [23:43:54] [TaskExecutor/INFO]: 插件数量: 15
[MCDR] [23:43:54] [TaskExecutor/INFO]: 服务端 PID: 3580
[MCDR] [23:43:54] [TaskExecutor/INFO]:   cmd.exe: 3580
[MCDR] [23:43:54] [TaskExecutor/INFO]:   └── pwsh.exe: 22492
[MCDR] [23:43:54] [TaskExecutor/INFO]:       └── java17.exe: 16312
[MCDR] [23:43:54] [TaskExecutor/INFO]: 消息队列负载: 0/2048
[MCDR] [23:43:54] [TaskExecutor/INFO]: 线程数: 6
[MCDR] [23:43:54] [TaskExecutor/INFO]:   - MainThread
[MCDR] [23:43:54] [TaskExecutor/INFO]:   - WatchDog
[MCDR] [23:43:54] [TaskExecutor/INFO]:   - TaskExecutor
[MCDR] [23:43:54] [TaskExecutor/INFO]:   - APR@14c0
[MCDR] [23:43:54] [TaskExecutor/INFO]:   - ConsoleHandler
[MCDR] [23:43:54] [TaskExecutor/INFO]:   - UpdateHelper
```

**Comment by Fallen-Breath** [comment]
traceback 中的 `Literal('tp').QuotableText('name').runs(lambda src, ctx: tp_to(src, ctx)))` 并不存在于 LocationMarker 的代码中。插件文件被篡改，请自行解决问题

附 LocationMarker v1.3.1、v1.3.2 的哈希值

```
$ sha256sum LocationMarker*
b23fde3f1b6183c8c9f053558452796d012944528ad4a1b2d2dfebbaa979428d *LocationMarker-v1.3.1.mcdr
b01e5c32e5530d18793c22f5ea098800aedc2e36f3fb1251e2a0db1c096beee0 *LocationMarker-v1.3.2.mcdr
```

**Comment by shenjackyuanjie** [comment]
~~issue 还能 close 两次的吗（~~
哦，修改理由是吧，确实
